AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

service: olin-bear-meets-alexa

provider:
  name: aws
  runtime: python3.6

functions:
  lambda_handler:
    name: OlinABE
    handler: lambda_function.lambda_handler

Resources:
  OlinABE:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::192019071823:role/service-role/olin-library'
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill

package:
  exclude:
    - .gitignore
    - documentation
    - secrets.yml
    - README.md
